### ISSUE TITLE
Can't create some objects (PD-extended / OSX 10.9)

### ISSUE THREAD

**Issue by zepadovani** [CICM/HoaLibrary#25]
Hi, 
it seems that some objects are missing in the puredata binary of your site (http://www.mshparisnord.fr/hoalibrary/en/downloads/puredata/)

hoa.pi
hoa.connect
hoa.map
hoa.in
hoa.out
...

Also, I tried to compily by myself ater compiling CicmWrapper... I've successfully build the external but when I try this one instead of your binary the pd window throws me (it seems to be something stupid that I'm missing...):

/Users/ze/pd-externals/HoaLibrary/hoa.library.pd_darwin: dlopen(/Users/ze/pd-externals/HoaLibrary/hoa.library.pd_darwin, 10): Symbol not found: _pd_this
  Referenced from: /Users/ze/pd-externals/HoaLibrary/hoa.library.pd_darwin
  Expected in: flat namespace
 in /Users/ze/pd-externals/HoaLibrary/hoa.library.pd_darwin
[import]: can't load library in 'hoa.library'

thanks!

BTW: the "Windows / Mac / Linux (v2.1 for PD & PD-Extented) (24/07/2014)" link in the english version of the pd page (http://www.mshparisnord.fr/hoalibrary/en/downloads/puredata/) is wrong, it directs to the windows/max version of the library.

**Comment by pierreguillot** [comment]
Hi,
Since Pure Data extended is not developed anymore there are two binaries, one for Vanilla and another one for extended. I've try the last release on several computers and there are no missing externals, perhaps you don't use the right binary (the binary for extended is in the folder "Hoa/externals/MacOs/pd-extended") or perhaps the path to the library is not properly defined. If you have the console errors this would be helpful. 
Anyway, if you know to compile, I suggest you to use the new repository https://github.com/CICM/HoaLibrary-PD. You should use the target "hoa" for vanilla and extended or "hoa-extended" for extended only. And the binary file will always be in the folder "Hoa/externals/MacOs/pd-extended" of the "package" folder. You currently use the vanilla binary (pd_this is only available in Vanilla)

Thanks for feedbacks.

**Comment by zepadovani** [comment]
2015-05-21 4:16 GMT-03:00 Pierre Guillot <notifications@github.com>:

> Hi,
> Since Pure Data extended is not developed anymore there are two binaries,
> one for Vanilla and another one for extended. I've try the last release on
> several computers and there are no missing externals, perhaps you don't use
> the right binary (the binary for extended is in the folder
> "Hoa/externals/MacOs/pd-extended") or perhaps the path to the library is
> not properly defined. If you have the console errors this would be helpful.
>
That's weird. I used the proper extended version.
Now I tried installing the last Vanilla and use the your binary of the
vanilla hoa library.
It gives me this error on startup:

"/Users/ze/pd-vanilla-externals/hoa/hoa.library.pd_darwin:
dlopen(/Users/ze/pd-vanilla-externals/hoa/hoa.library.pd_darwin, 10):
Symbol not found: _canvas_list
  Referenced from: /Users/ze/pd-vanilla-externals/hoa/hoa.library.pd_darwin
  Expected in: flat namespace
 in /Users/ze/pd-vanilla-externals/hoa/hoa.library.pd_darwin
hoa.library: can't load library"

I'll try to compile later and see what I get.

In any case, thank you!

**Comment by pierreguillot** [comment]
You can look at the new release.
